### ISSUE TITLE
Error: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by recursionbane** [jla/gpt-shell#1]
Interesting project, I can see this becoming the future of all shell interaction.

Seeing this error occasionally:

![image](https://user-images.githubusercontent.com/9662059/228025252-34e38ffb-7572-41d4-8c85-eee6954aab52.png)

Is it erroring out here?

```
                if action == 'shell':
                    ret = subprocess.run(params, shell=True, text=True, capture_output=True)
                    output = ret.stdout + ret.stderr + f'Return code: {ret.returncode}'
```

**Comment by jla** [comment]
It's the 'Action' parser, at https://github.com/jla/gpt-shell/blob/main/main.py#L106 
```python
if line.startswith('Action:'):
    _, action, params = [p.strip() for p in line.split(':', 2)]
```
Currently, it's quite fragile and fails when encountering 'creative' responses.

One question, are you using gpt-3.5-turbo or gpt-4?  I show that kind of imaginative output (where it send the Action in creative ways and responds to itself with observations) way more often on gpt-3.5.

A part of making the Action parser a little bit more  resilient the only thing that can be done is changing  the PROMPT to insist that GPT should send the Action command using the correct syntax.

**Comment by recursionbane** [comment]
I'm using gpt-3.5-turbo, don't yet have access to gpt-4.

Can we add a post-processing step (instead of updating the prompt) to ask GPT to reformat to the correct syntax?

I've found that more, smaller, requests are more reliable than shoehorning a mass of constraints into the original prompt.
